In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

### Here I will look at the Discharge to the Community rates for North Carolina and the nation.  I'll also merge with data on region and ownership types.

2023 DTC Rates:

In [2]:
IRF_provider_data_June_23 = pd.read_csv('../data/Inpatient_Rehabilitation_Facility-Provider_Data_Jun2023.csv')
IRF_provider_data_June_23.head()

,CMS Certification Number (CCN),Facility Name,Address Line 1,Address Line 2,City,State,Zip Code,County Name,Phone Number,CMS Region,Measure Code,Score,Footnote,Start Date,End Date,Measure Date Range
0,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_CI_LOWER,0.436,-,07/01/2021,06/30/2022,-
1,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_CI_UPPER,3.313,-,07/01/2021,06/30/2022,-
2,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_COMP_PERF,No Different than the National Benchmark,-,07/01/2021,06/30/2022,-
3,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_DOPC_DAYS,2694,-,07/01/2021,06/30/2022,-
4,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_ELIGCASES,2.912,-,07/01/2021,06/30/2022,-

In [3]:
IRF_provider_data_June_23=IRF_provider_data_June_23[['CMS Certification Number (CCN)','State','County Name','CMS Region', 'Measure Code','Score']]
IRF_provider_data_June_23.head()

,CMS Certification Number (CCN),State,County Name,CMS Region,Measure Code,Score
0,013025,AL,Jefferson,4,I_006_01_CI_LOWER,0.436
1,013025,AL,Jefferson,4,I_006_01_CI_UPPER,3.313
2,013025,AL,Jefferson,4,I_006_01_COMP_PERF,No Different than the National Benchmark
3,013025,AL,Jefferson,4,I_006_01_DOPC_DAYS,2694
4,013025,AL,Jefferson,4,I_006_01_ELIGCASES,2.912

In [4]:
NC_DTC_Rate_23=IRF_provider_data_June_23.loc[(IRF_provider_data_June_23['Measure Code']=='I_019_02_DTC_OBS_RATE')& (IRF_provider_data_June_23['State']=='NC')]
NC_DTC_Rate_23.head()

,CMS Certification Number (CCN),State,County Name,CMS Region,Measure Code,Score
47855,343025,NC,Buncombe,4,I_019_02_DTC_OBS_RATE,66.30
47923,343026,NC,Mecklenburg,4,I_019_02_DTC_OBS_RATE,67.79
47991,343027,NC,Forsyth,4,I_019_02_DTC_OBS_RATE,67.45
48059,34T004,NC,Guilford,4,I_019_02_DTC_OBS_RATE,76.40
48127,34T008,NC,Scotland,4,I_019_02_DTC_OBS_RATE,73.08

In [5]:
not_available=NC_DTC_Rate_23.loc[NC_DTC_Rate_23['Score']=='Not Available']

In [6]:
NC_DTC_Rate_23= NC_DTC_Rate_23.drop(not_available.index, axis=0).reset_index(drop=True)

In [7]:
NC_DTC_Rate_23['Score']=NC_DTC_Rate_23['Score'].astype(str).astype(float)

In [8]:
Avg_NC_DTC_Rate_23=NC_DTC_Rate_23.groupby('County Name')['Score'].mean().to_frame().reset_index()

In [9]:
Avg_NC_DTC_Rate_23=Avg_NC_DTC_Rate_23.rename(columns={'Score':'2023_Score','County Name':'County/Parish'})

In [10]:
Avg_NC_DTC_Rate_23

   County/Parish  2023_Score
0       Buncombe      66.300
1        Catawba      71.795
2         Craven      80.700
3     Cumberland      66.110
4         Durham      63.220
5        Forsyth      67.355
6       Guilford      75.040
7         Lenoir      63.930
8    Mecklenburg      65.995
9          Moore      68.250
10          Nash      72.450
11   New Hanover      71.690
12        Orange      68.390
13          Pitt      66.450
14         Rowan      76.320
15      Scotland      73.080
16         Vance      66.670
17          Wake      68.410

2024 DTC Rates:

In [11]:
IRF_provider_data_June_24 = pd.read_csv('../data/Inpatient_Rehabilitation_Facility-Provider_Data_Jun2024.csv')
IRF_provider_data_June_24.head(1)

,CMS Certification Number (CCN),Provider Name,Address Line 1,Address Line 2,City/Town,State,ZIP Code,County/Parish,Telephone Number,CMS Region,Measure Code,Score,Footnote,Start Date,End Date,Measure Date Range
0,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_CI_LOWER,0.773,-,07/01/2022,06/30/2023,-

In [12]:
IRF_provider_data_June_24=IRF_provider_data_June_24[['CMS Certification Number (CCN)','County/Parish','State', 'Measure Code','Score']]
IRF_provider_data_June_24.head(1)

  CMS Certification Number (CCN) County/Parish State       Measure Code  Score
0                         013025     Jefferson    AL  I_006_01_CI_LOWER  0.773

In [13]:
NC_DTC_24=IRF_provider_data_June_24.loc[(IRF_provider_data_June_24['Measure Code']=='I_019_02_DTC_OBS_RATE') & (IRF_provider_data_June_24['State']=='NC')]
NC_DTC_24.head()

,CMS Certification Number (CCN),County/Parish,State,Measure Code,Score
48195,343025,Buncombe,NC,I_019_02_DTC_OBS_RATE,70.98
48263,343026,Mecklenburg,NC,I_019_02_DTC_OBS_RATE,69.14
48331,343027,Forsyth,NC,I_019_02_DTC_OBS_RATE,68.33
48399,34T004,Guilford,NC,I_019_02_DTC_OBS_RATE,73.81
48467,34T008,Scotland,NC,I_019_02_DTC_OBS_RATE,Not Available

In [14]:
not_available= NC_DTC_24.loc[NC_DTC_24['Score']=='Not Available']

In [15]:
NC_DTC_24=NC_DTC_24.drop(not_available.index, axis=0).reset_index(drop=True)

In [16]:
NC_DTC_24['Score']=NC_DTC_24['Score'].astype(str).astype(float)

In [17]:
Avg_NC_DTC_24= NC_DTC_24.groupby('County/Parish')['Score'].mean().to_frame()

In [18]:
Avg_NC_DTC_24=Avg_NC_DTC_24.rename(columns={'Score':'2024_Score'})

In [19]:
Avg_NC_DTC_24=Avg_NC_DTC_24.reset_index()
Avg_NC_DTC_24

   County/Parish  2024_Score
0       Buncombe      70.980
1        Catawba      71.030
2         Craven      78.640
3     Cumberland      69.240
4         Durham      69.640
5        Forsyth      69.205
6       Guilford      72.480
7         Lenoir      65.470
8    Mecklenburg      67.015
9          Moore      73.530
10          Nash      76.110
11   New Hanover      72.410
12        Orange      67.960
13          Pitt      61.890
14         Rowan      75.900
15         Vance      70.970
16          Wake      69.270

2025 DTC Rates:

In [20]:
IRF_provider_data_June_25 = pd.read_csv('../data/Inpatient_Rehabilitation_Facility_Provider_Data_Jun2025.csv')
IRF_provider_data_June_25

,CMS Certification Number (CCN),Provider Name,Address Line 1,Address Line 2,City/Town,State,ZIP Code,County/Parish,Telephone Number,CMS Region,Measure Code,Score,Footnote,Start Date,End Date,Measure Date Range
0,13025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_CI_LOWER,0.821,-,7/1/2023,6/30/2024,-
1,13025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_CI_UPPER,4.213,-,7/1/2023,6/30/2024,-
2,13025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_COMP_PERF,No Different than the National Benchmark,-,7/1/2023,6/30/2024,-
3,13025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_DOPC_DAYS,"2,743",-,7/1/2023,6/30/2024,-
4,13025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_ELIGCASES,2.962,-,7/1/2023,6/30/2024,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83295,743031,HORIZON MEDICAL CENTER OF MCKINNEY LLC,6601 W UNIVERSITY DRIVE,-,MC KINNEY,TX,75071,Collin,(469) 907-1355,6,I_025_02_NUMERATOR,Not Available,2,10/1/2023,9/30/2024,-
83296,743031,HORIZON MEDICAL CENTER OF MCKINNEY LLC,6601 W UNIVERSITY DRIVE,-,MC KINNEY,TX,75071,Collin,(469) 907-1355,6,I_025_02_OBS_RATE,Not Available,2,10/1/2023,9/30/2024,-
83297,743031,HORIZON MEDICAL CENTER OF MCKINNEY LLC,6601 W UNIVERSITY DRIVE,-,MC KINNEY,TX,75071,Collin,(469) 907-1355,6,I_026_01_DENOMINATOR,Not Available,2,10/1/2023,9/30/2024,-
83298,743031,HORIZON MEDICAL CENTER OF MCKINNEY LLC,6601 W UNIVERSITY DRIVE,-,MC KINNEY,TX,75071,Collin,(469) 907-1355,6,I_026_01_NUMERATOR,Not Available,2,10/1/2023,9/30/2024,-
83299,743031,HORIZON MEDICAL CENTER OF MCKINNEY LLC,6601 W UNIVERSITY DRIVE,-,MC KINNEY,TX,75071,Collin,(469) 907-1355,6,I_026_01_OBS_RATE,Not Available,2,10/1/2023,9/30/2024,-

In [21]:
IRF_provider_data_June_25=IRF_provider_data_June_25[['CMS Certification Number (CCN)','County/Parish','State', 'Measure Code','Score']]

In [22]:
NC_DTC_25=IRF_provider_data_June_25.loc[(IRF_provider_data_June_25['Measure Code']=='I_019_02_DTC_OBS_RATE') & (IRF_provider_data_June_25['State']=='NC')]
NC_DTC_25.head()

,CMS Certification Number (CCN),County/Parish,State,Measure Code,Score
48594,343025,Buncombe,NC,I_019_02_DTC_OBS_RATE,70.99
48662,343026,Mecklenburg,NC,I_019_02_DTC_OBS_RATE,67.24
48730,343027,Forsyth,NC,I_019_02_DTC_OBS_RATE,69.6
48798,34T004,Guilford,NC,I_019_02_DTC_OBS_RATE,78.43
48866,34T008,Scotland,NC,I_019_02_DTC_OBS_RATE,Not Available

In [23]:
not_available= NC_DTC_25.loc[NC_DTC_25['Score']=='Not Available']

In [24]:
NC_DTC_25=NC_DTC_25.drop(not_available.index, axis=0).reset_index(drop=True)

In [25]:
NC_DTC_25['Score']=NC_DTC_25['Score'].astype(str).astype(float)

In [26]:
Avg_NC_DTC_25= NC_DTC_25.groupby('County/Parish')['Score'].mean().to_frame().reset_index()

In [27]:
Avg_NC_DTC_25=Avg_NC_DTC_25.rename(columns={'Score':'2025_Score'})
Avg_NC_DTC_25

   County/Parish  2025_Score
0       Buncombe      70.990
1        Catawba      72.135
2         Craven      77.580
3     Cumberland      69.970
4         Durham      70.150
5        Forsyth      71.590
6       Guilford      73.085
7         Lenoir      60.430
8    Mecklenburg      67.590
9          Moore      82.900
10          Nash      74.610
11   New Hanover      74.050
12        Orange      69.110
13          Pitt      61.660
14         Rowan      76.840
15         Vance      71.530
16          Wake      69.810

In [28]:
dfs=[Avg_NC_DTC_Rate_23, Avg_NC_DTC_24, Avg_NC_DTC_25]

Avg_NC_DTC_Merged = dfs[0]

for i in range(1, len(dfs)):
    Avg_NC_DTC_Merged= pd.merge(Avg_NC_DTC_Merged, dfs[i], on = 'County/Parish', how ='inner')


Avg_NC_DTC_Merged

   County/Parish  2023_Score  2024_Score  2025_Score
0       Buncombe      66.300      70.980      70.990
1        Catawba      71.795      71.030      72.135
2         Craven      80.700      78.640      77.580
3     Cumberland      66.110      69.240      69.970
4         Durham      63.220      69.640      70.150
5        Forsyth      67.355      69.205      71.590
6       Guilford      75.040      72.480      73.085
7         Lenoir      63.930      65.470      60.430
8    Mecklenburg      65.995      67.015      67.590
9          Moore      68.250      73.530      82.900
10          Nash      72.450      76.110      74.610
11   New Hanover      71.690      72.410      74.050
12        Orange      68.390      67.960      69.110
13          Pitt      66.450      61.890      61.660
14         Rowan      76.320      75.900      76.840
15         Vance      66.670      70.970      71.530
16          Wake      68.410      69.270      69.810

Looking at national data for discharge to the community rates:

In [29]:
National_Data_25= pd.read_csv('../data/Inpatient_Rehabilitation_Facility_National_Data_Jun2025.csv')

In [30]:
National_DTC_Rate_25=National_Data_25.loc[National_Data_25['Measure Code']=='I_019_02_DTC_NATL_OBS_RATE']

In [31]:
National_DTC_Rate_25=National_DTC_Rate_25.rename(columns={'Score':'2025_Score'}).drop(columns=['Measure Code','Footnote','Start Date','End Date','Measure Date Range'])
National_DTC_Rate_25

   CMS Certification Number (CCN) 2025_Score
16                         NATION      66.95

In [32]:
National_Data_24= pd.read_csv('../data/Inpatient_Rehabilitation_Facility-National_Data_Jun2024.csv')

In [33]:
National_DTC_Rate_24=National_Data_24.loc[National_Data_24['Measure Code']=='I_019_02_DTC_NATL_OBS_RATE']

In [34]:
National_DTC_Rate_24=National_DTC_Rate_24.rename(columns={'Score':'2024_Score'}).drop(columns=['Measure Code','Footnote','Start Date','End Date','Measure Date Range'])
National_DTC_Rate_24

   CMS Certification Number (CCN) 2024_Score
19                         NATION      66.93

In [35]:
National_Data_23=pd.read_csv('../data/Inpatient_Rehabilitation_Facility-National_Data_Jun2023.csv')

In [36]:
National_DTC_Rate_23=National_Data_23.loc[National_Data_23['Measure Code']=='I_019_02_DTC_NATL_OBS_RATE']

In [37]:
National_DTC_Rate_23=National_DTC_Rate_23.rename(columns={'Score':'2023_Score'}).drop(columns=['Measure Code','Footnote','Start Date','End Date','Measure Date Range'])
National_DTC_Rate_23

   CMS Certification Number (CCN) 2023_Score
19                         NATION      66.21

In [38]:
dfs=[National_DTC_Rate_23, National_DTC_Rate_24, National_DTC_Rate_25]

National_DTC_Merged = dfs[0]

for i in range(1, len(dfs)):
    National_DTC_Merged= pd.merge(National_DTC_Merged, dfs[i], on = 'CMS Certification Number (CCN)', how ='inner')


National_DTC_Merged

  CMS Certification Number (CCN) 2023_Score 2024_Score 2025_Score
0                         NATION      66.21      66.93      66.95

In [39]:
National_DTC_Merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   CMS Certification Number (CCN)  1 non-null      object
 1   2023_Score                      1 non-null      object
 2   2024_Score                      1 non-null      object
 3   2025_Score                      1 non-null      object
dtypes: object(4)
memory usage: 164.0+ bytes

In [40]:
National_DTC_Merged= National_DTC_Merged[['2023_Score','2024_Score','2025_Score']].astype(str).astype(float)
National_DTC_Merged

   2023_Score  2024_Score  2025_Score
0       66.21       66.93       66.95

In [41]:
National_DTC_Merged.to_csv('National_DTC_Merged.csv', index=False)

In [42]:
National_DTC_Merged['Overall Avg']=National_DTC_Merged[['2023_Score','2024_Score','2025_Score']].mean(axis=1)
National_DTC_Merged

   2023_Score  2024_Score  2025_Score  Overall Avg
0       66.21       66.93       66.95    66.696667

#### Finding the % change in scores, then merging with regional/ownership data

In [43]:
Avg_NC_DTC_Merged.head()

  County/Parish  2023_Score  2024_Score  2025_Score
0      Buncombe      66.300       70.98      70.990
1       Catawba      71.795       71.03      72.135
2        Craven      80.700       78.64      77.580
3    Cumberland      66.110       69.24      69.970
4        Durham      63.220       69.64      70.150

In [44]:
Avg_NC_DTC_Merged['Pct change']= ((Avg_NC_DTC_Merged['2025_Score']-Avg_NC_DTC_Merged['2023_Score'])/(Avg_NC_DTC_Merged['2023_Score'])) * 100
Avg_NC_DTC_Merged

   County/Parish  2023_Score  2024_Score  2025_Score  Pct change
0       Buncombe      66.300      70.980      70.990    7.073906
1        Catawba      71.795      71.030      72.135    0.473571
2         Craven      80.700      78.640      77.580   -3.866171
3     Cumberland      66.110      69.240      69.970    5.838754
4         Durham      63.220      69.640      70.150   10.961721
5        Forsyth      67.355      69.205      71.590    6.287581
6       Guilford      75.040      72.480      73.085   -2.605277
7         Lenoir      63.930      65.470      60.430   -5.474738
8    Mecklenburg      65.995      67.015      67.590    2.416850
9          Moore      68.250      73.530      82.900   21.465201
10          Nash      72.450      76.110      74.610    2.981366
11   New Hanover      71.690      72.410      74.050    3.291951
12        Orange      68.390      67.960      69.110    1.052785
13          Pitt      66.450      61.890      61.660   -7.208427
14         Rowan      76.320      75.900      76.840    0.681342
15         Vance      66.670      70.970      71.530    7.289636
16          Wake      68.410      69.270      69.810    2.046484

In [45]:
Avg_NC_DTC_Merged.to_csv('Avg_NC_DTC_Merged.csv', index=False)

#### Merging North Carolina DTC w/ pct change and region/owndership type data frames:

In [90]:
ownership_type= pd.read_csv('../data/Inpatient_Rehabilitation_Facility-General_Information_Jun2025.csv')
ownership_type.head()

,CMS Certification Number (CCN),Provider Name,Address Line 1,Address Line 2,City/Town,State,ZIP Code,County/Parish,Telephone Number,CMS Region,Ownership Type,Certification Date
0,13025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,For profit,10/1/1983
1,13028,ENCOMPASS REHABILITATION HOSPITAL OF MONTGOMERY,4465 NARROW LANE RD,-,MONTGOMERY,AL,36116,Montgomery,(334) 284-7821,4,For profit,5/11/1987
2,13029,ENCOMPASS HEALTH REHABILITATION HOSPITAL NORTH...,1490 HIGHWAY 72 E,-,HUNTSVILLE,AL,35811,Madison,(205) 535-2300,4,For profit,6/4/1987
3,13030,ENCOMPASS HEALTH REHABILITATION HOSPITAL OF DO...,1736 EAST MAIN STREET,-,DOTHAN,AL,36301,Houston,(334) 712-6333,4,For profit,5/12/1994
4,13031,ENCOMPASS HEALTH REHABILITATION HOSPITAL OF SH...,900 OAK MOUNTAIN COMMONS LANE,-,PELHAM,AL,35124,Shelby,(205) 216-7621,4,For profit,5/25/2018

In [91]:
ownership_type=ownership_type[['State','County/Parish','Ownership Type']]

In [92]:
ownership_type=ownership_type.loc[ownership_type['State']=='NC'].drop(columns='State')
ownership_type

    County/Parish Ownership Type
714      Buncombe     Non-profit
715   Mecklenburg     Government
716       Forsyth     For profit
717      Guilford     Non-profit
718      Scotland     Non-profit
719       Forsyth     Non-profit
720         Rowan     Non-profit
721        Lenoir     Non-profit
722    Cumberland     Non-profit
723          Pitt     Non-profit
724       Forsyth     Non-profit
725   Mecklenburg     Non-profit
726        Orange     Government
727          Wake     Non-profit
728      Guilford     Non-profit
729         Surry     Non-profit
730   Mecklenburg     Government
731   Mecklenburg     Government
732         Moore     Non-profit
733       Catawba     For profit
734        Craven     Government
735         Vance     For profit
736   New Hanover     Government
737       Catawba     Non-profit
738          Nash     Government
739        Durham     Government

In [112]:
Region=pd.read_csv('../data/population-projections-by-race-age-groups-6.csv')
Region

,fips,County,Region,COG,MSA,Year,Race,Group N,Age 0 to 2,Age 3 to 4,...,medage,Age 0 to 17,Age 18 to 24,Age 25 to 44,Age 45 to 64,Age 65 Plus,geom,Estimate/Projection,Vintage,geo_point_2d
0,37035,Catawba,Western North Carolina,Western Piedmont Council of Governments,Hickory-Lenoir-Morganton,2023,Other,1,531,362,...,22.317797,3308,884,1166,1376,1091,"{""coordinates"":[[[[-81.535403,35.568136999],[-...",Estimate,2023,"35.66204217649048, -81.21507090050821"
1,37051,Cumberland,Eastern North Carolina,Mid-Carolina Council of Governments,Fayetteville,2025,White,1,7186,4579,...,34.145808,37437,20524,45974,31806,25406,"{""coordinates"":[[[[-78.617114,35.245717999],[-...",Projection,2024,"35.048730278966026, -78.82767910401198"
2,37049,Craven,Eastern North Carolina,Eastern Carolina Council of Governments,Non-Metropolitan,2023,Asian & Pacific Islander,1,137,99,...,38.464789,795,283,1191,854,679,"{""coordinates"":[[[[-77.473692,35.228984999],[-...",Estimate,2023,"35.11768626049315, -77.08200556349992"
3,37067,Forsyth,Central North Carolina,Piedmont Triad Council of Governments,Winston-Salem,2024,White,1,7734,4831,...,42.034691,50136,25577,63813,67530,53654,"{""coordinates"":[[[[-80.452656,36.241650999],[-...",Projection,2024,"36.13062541993835, -80.25630963982927"
4,37107,Lenoir,Eastern North Carolina,Eastern Carolina Council of Governments,Non-Metropolitan,2025,White,1,915,595,...,45.065476,5342,2196,7003,7452,7133,"{""coordinates"":[[[[-77.806248,35.368753999],[-...",Projection,2024,"35.23877244974368, -77.64124985899035"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,37183,Wake,Central North Carolina,Central Pines Regional Council,Raleigh-Cary,2024,Asian & Pacific Islander,1,3259,2070,...,39.229246,23059,11576,40186,34773,11414,"{""coordinates"":[[[[-78.751273,36.070833999],[-...",Projection,2024,"35.79031331872891, -78.65028009124825"
251,37183,Wake,Central North Carolina,Central Pines Regional Council,Raleigh-Cary,2024,Black,1,7913,5614,...,35.444985,53130,21552,62833,56731,25607,"{""coordinates"":[[[[-78.751273,36.070833999],[-...",Projection,2024,"35.79031331872891, -78.65028009124825"
252,37147,Pitt,Eastern North Carolina,Mid-East Commission,Greenville,2025,Black,1,2643,1755,...,34.071379,15643,8437,20297,12946,8576,"{""coordinates"":[[[[-77.700692,35.652294999],[-...",Projection,2024,"35.59329885449204, -77.37449649585241"
253,37183,Wake,Central North Carolina,Central Pines Regional Council,Raleigh-Cary,2025,Asian & Pacific Islander,1,3425,2093,...,39.725061,23218,12272,41271,37225,12371,"{""coordinates"":[[[[-78.751273,36.070833999],[-...",Projection,2024,"35.79031331872891, -78.65028009124825"
254,37159,Rowan,Central North Carolina,Centralina Council of Governments,Charlotte-Concord-Gastonia (NC),2025,Black,1,819,581,...,36.307317,5868,2606,7169,5880,3659,"{""coordinates"":[[[[-80.707824,35.852960999],[-...",Projection,2024,"35.63942562816136, -80.52474972960941"

In [113]:
Region=Region.rename(columns={'County':'County/Parish'})
Region.head(1)

,fips,County/Parish,Region,COG,MSA,Year,Race,Group N,Age 0 to 2,Age 3 to 4,...,medage,Age 0 to 17,Age 18 to 24,Age 25 to 44,Age 45 to 64,Age 65 Plus,geom,Estimate/Projection,Vintage,geo_point_2d
0,37035,Catawba,Western North Carolina,Western Piedmont Council of Governments,Hickory-Lenoir-Morganton,2023,Other,1,531,362,...,22.317797,3308,884,1166,1376,1091,"{""coordinates"":[[[[-81.535403,35.568136999],[-...",Estimate,2023,"35.66204217649048, -81.21507090050821"

In [131]:
DTC_Region_Ownership_Type= pd.merge(ownership_type,Region,
                                    on='County/Parish',
                                    how='inner')
DTC_Region_Ownership_Type.head()

,County/Parish,Ownership Type,fips,Region,COG,MSA,Year,Race,Group N,Age 0 to 2,...,medage,Age 0 to 17,Age 18 to 24,Age 25 to 44,Age 45 to 64,Age 65 Plus,geom,Estimate/Projection,Vintage,geo_point_2d
0,Buncombe,Non-profit,37021,Western North Carolina,Land-of-Sky Regional Council,Asheville,2025,White,1,5896,...,44.662553,39624,17875,66389,63843,57666,"{""coordinates"":[[[[-82.408602,35.818177999],[-...",Projection,2024,"35.611177737847356, -82.53010688873636"
1,Buncombe,Non-profit,37021,Western North Carolina,Land-of-Sky Regional Council,Asheville,2024,Black,1,518,...,36.731801,3815,1489,4717,3728,2861,"{""coordinates"":[[[[-82.408602,35.818177999],[-...",Projection,2024,"35.611177737847356, -82.53010688873636"
2,Buncombe,Non-profit,37021,Western North Carolina,Land-of-Sky Regional Council,Asheville,2023,White,1,5877,...,44.161786,40236,17473,65798,62998,54841,"{""coordinates"":[[[[-82.408602,35.818177999],[-...",Estimate,2023,"35.611177737847356, -82.53010688873636"
3,Buncombe,Non-profit,37021,Western North Carolina,Land-of-Sky Regional Council,Asheville,2023,Black,1,529,...,36.449115,3861,1464,4669,3726,2797,"{""coordinates"":[[[[-82.408602,35.818177999],[-...",Estimate,2023,"35.611177737847356, -82.53010688873636"
4,Buncombe,Non-profit,37021,Western North Carolina,Land-of-Sky Regional Council,Asheville,2025,Other,1,678,...,33.542254,3946,1291,3898,2466,2066,"{""coordinates"":[[[[-82.408602,35.818177999],[-...",Projection,2024,"35.611177737847356, -82.53010688873636"

In [132]:
DTC_Region_Ownership_Type.columns

Index(['County/Parish', 'Ownership Type', 'fips', 'Region', 'COG', 'MSA',
       'Year', 'Race', 'Group N', 'Age 0 to 2', 'Age 3 to 4', 'Age 5',
       'Age 6 to 9', 'Age 10 to 13', 'Age 14', 'Age 15', 'Age 16 to 17',
       'Age 18 to 19', 'Age 20 to 24', 'Age 25 to 34', 'Age 35 to 44',
       'Age 45 to 54', 'Age 55 to 59', 'Age 60 to 64', 'Age 65 to 74',
       'Age 75 to 84', 'Age 85 to 99', 'Age 100', 'Total', 'medage',
       'Age 0 to 17', 'Age 18 to 24', 'Age 25 to 44', 'Age 45 to 64',
       'Age 65 Plus', 'geom', 'Estimate/Projection', 'Vintage',
       'geo_point_2d'],
      dtype='object')

In [133]:
DTC_Region_Ownership_Type=DTC_Region_Ownership_Type[['County/Parish','Ownership Type','Region']]
DTC_Region_Ownership_Type

    County/Parish Ownership Type                  Region
0        Buncombe     Non-profit  Western North Carolina
1        Buncombe     Non-profit  Western North Carolina
2        Buncombe     Non-profit  Western North Carolina
3        Buncombe     Non-profit  Western North Carolina
4        Buncombe     Non-profit  Western North Carolina
..            ...            ...                     ...
355        Durham     Government  Central North Carolina
356        Durham     Government  Central North Carolina
357        Durham     Government  Central North Carolina
358        Durham     Government  Central North Carolina
359        Durham     Government  Central North Carolina

[360 rows x 3 columns]

In [134]:
DTC_Region_Ownership_Type=pd.merge(DTC_Region_Ownership_Type, Avg_NC_DTC_Merged,
                                   on='County/Parish',
                                   how='inner')
DTC_Region_Ownership_Type

,County/Parish,Ownership Type,Region,2023_Score,2024_Score,2025_Score,Pct change
0,Buncombe,Non-profit,Western North Carolina,66.30,70.98,70.99,7.073906
1,Buncombe,Non-profit,Western North Carolina,66.30,70.98,70.99,7.073906
2,Buncombe,Non-profit,Western North Carolina,66.30,70.98,70.99,7.073906
3,Buncombe,Non-profit,Western North Carolina,66.30,70.98,70.99,7.073906
4,Buncombe,Non-profit,Western North Carolina,66.30,70.98,70.99,7.073906
...,...,...,...,...,...,...,...
355,Durham,Government,Central North Carolina,63.22,69.64,70.15,10.961721
356,Durham,Government,Central North Carolina,63.22,69.64,70.15,10.961721
357,Durham,Government,Central North Carolina,63.22,69.64,70.15,10.961721
358,Durham,Government,Central North Carolina,63.22,69.64,70.15,10.961721
359,Durham,Government,Central North Carolina,63.22,69.64,70.15,10.961721

In [135]:
DTC_Region_Ownership_Type=DTC_Region_Ownership_Type.rename(columns={'Pct change':'Pct DTC change'}).reset_index(drop=True)
DTC_Region_Ownership_Type

,County/Parish,Ownership Type,Region,2023_Score,2024_Score,2025_Score,Pct DTC change
0,Buncombe,Non-profit,Western North Carolina,66.30,70.98,70.99,7.073906
1,Buncombe,Non-profit,Western North Carolina,66.30,70.98,70.99,7.073906
2,Buncombe,Non-profit,Western North Carolina,66.30,70.98,70.99,7.073906
3,Buncombe,Non-profit,Western North Carolina,66.30,70.98,70.99,7.073906
4,Buncombe,Non-profit,Western North Carolina,66.30,70.98,70.99,7.073906
...,...,...,...,...,...,...,...
355,Durham,Government,Central North Carolina,63.22,69.64,70.15,10.961721
356,Durham,Government,Central North Carolina,63.22,69.64,70.15,10.961721
357,Durham,Government,Central North Carolina,63.22,69.64,70.15,10.961721
358,Durham,Government,Central North Carolina,63.22,69.64,70.15,10.961721
359,Durham,Government,Central North Carolina,63.22,69.64,70.15,10.961721

In [136]:
DTC_Region_Ownership_Type=DTC_Region_Ownership_Type.drop_duplicates()

In [137]:
DTC_Region_Ownership_Type=DTC_Region_Ownership_Type.reset_index(drop=True)
DTC_Region_Ownership_Type

,County/Parish,Ownership Type,Region,2023_Score,2024_Score,2025_Score,Pct DTC change
0,Buncombe,Non-profit,Western North Carolina,66.300,70.980,70.990,7.073906
1,Mecklenburg,Government,Central North Carolina,65.995,67.015,67.590,2.416850
2,Forsyth,For profit,Central North Carolina,67.355,69.205,71.590,6.287581
3,Guilford,Non-profit,Central North Carolina,75.040,72.480,73.085,-2.605277
4,Forsyth,Non-profit,Central North Carolina,67.355,69.205,71.590,6.287581
5,Rowan,Non-profit,Central North Carolina,76.320,75.900,76.840,0.681342
6,Lenoir,Non-profit,Eastern North Carolina,63.930,65.470,60.430,-5.474738
7,Cumberland,Non-profit,Eastern North Carolina,66.110,69.240,69.970,5.838754
8,Pitt,Non-profit,Eastern North Carolina,66.450,61.890,61.660,-7.208427
9,Mecklenburg,Non-profit,Central North Carolina,65.995,67.015,67.590,2.416850
10,Orange,Government,Central North Carolina,68.390,67.960,69.110,1.052785
11,Wake,Non-profit,Central North Carolina,68.410,69.270,69.810,2.046484
12,Moore,Non-profit,Central North Carolina,68.250,73.530,82.900,21.465201
13,Catawba,For profit,Western North Carolina,71.795,71.030,72.135,0.473571
14,Craven,Government,Eastern North Carolina,80.700,78.640,77.580,-3.866171
15,Vance,For profit,Central North Carolina,66.670,70.970,71.530,7.289636
16,New Hanover,Government,Eastern North Carolina,71.690,72.410,74.050,3.291951
17,Catawba,Non-profit,Western North Carolina,71.795,71.030,72.135,0.473571
18,Nash,Government,Eastern North Carolina,72.450,76.110,74.610,2.981366
19,Durham,Government,Central North Carolina,63.220,69.640,70.150,10.961721

In [138]:
DTC_Region_Ownership_Type=DTC_Region_Ownership_Type.drop_duplicates(subset=['Pct DTC change'], keep='first').reset_index(drop=True)
DTC_Region_Ownership_Type

,County/Parish,Ownership Type,Region,2023_Score,2024_Score,2025_Score,Pct DTC change
0,Buncombe,Non-profit,Western North Carolina,66.300,70.980,70.990,7.073906
1,Mecklenburg,Government,Central North Carolina,65.995,67.015,67.590,2.416850
2,Forsyth,For profit,Central North Carolina,67.355,69.205,71.590,6.287581
3,Guilford,Non-profit,Central North Carolina,75.040,72.480,73.085,-2.605277
4,Rowan,Non-profit,Central North Carolina,76.320,75.900,76.840,0.681342
5,Lenoir,Non-profit,Eastern North Carolina,63.930,65.470,60.430,-5.474738
6,Cumberland,Non-profit,Eastern North Carolina,66.110,69.240,69.970,5.838754
7,Pitt,Non-profit,Eastern North Carolina,66.450,61.890,61.660,-7.208427
8,Orange,Government,Central North Carolina,68.390,67.960,69.110,1.052785
9,Wake,Non-profit,Central North Carolina,68.410,69.270,69.810,2.046484
10,Moore,Non-profit,Central North Carolina,68.250,73.530,82.900,21.465201
11,Catawba,For profit,Western North Carolina,71.795,71.030,72.135,0.473571
12,Craven,Government,Eastern North Carolina,80.700,78.640,77.580,-3.866171
13,Vance,For profit,Central North Carolina,66.670,70.970,71.530,7.289636
14,New Hanover,Government,Eastern North Carolina,71.690,72.410,74.050,3.291951
15,Nash,Government,Eastern North Carolina,72.450,76.110,74.610,2.981366
16,Durham,Government,Central North Carolina,63.220,69.640,70.150,10.961721

In [139]:
DTC_Region_Ownership_Type.to_csv('DTC_Region_Ownership_Type.csv')

## Looking at Buncombe County specifically:

In [52]:
IRF_provider_data_June_23.head()

,CMS Certification Number (CCN),State,County Name,CMS Region,Measure Code,Score
0,013025,AL,Jefferson,4,I_006_01_CI_LOWER,0.436
1,013025,AL,Jefferson,4,I_006_01_CI_UPPER,3.313
2,013025,AL,Jefferson,4,I_006_01_COMP_PERF,No Different than the National Benchmark
3,013025,AL,Jefferson,4,I_006_01_DOPC_DAYS,2694
4,013025,AL,Jefferson,4,I_006_01_ELIGCASES,2.912

In [53]:
Buncombe_DTC_23=IRF_provider_data_June_23.loc[(IRF_provider_data_June_23['Measure Code']=='I_019_02_DTC_OBS_RATE')& (IRF_provider_data_June_23['County Name']=='Buncombe')]
Buncombe_DTC_23.head()

,CMS Certification Number (CCN),State,County Name,CMS Region,Measure Code,Score
47855,343025,NC,Buncombe,4,I_019_02_DTC_OBS_RATE,66.30

In [54]:
Buncombe_DTC_23=Buncombe_DTC_23.rename(columns={'County Name':'County/Parish'})

In [55]:
IRF_provider_data_June_24.head(1)

  CMS Certification Number (CCN) County/Parish State       Measure Code  Score
0                         013025     Jefferson    AL  I_006_01_CI_LOWER  0.773

In [56]:
Buncombe_DTC_24=IRF_provider_data_June_24.loc[(IRF_provider_data_June_24['Measure Code']=='I_019_02_DTC_OBS_RATE')& (IRF_provider_data_June_24['County/Parish']=='Buncombe')]
Buncombe_DTC_24.head()

,CMS Certification Number (CCN),County/Parish,State,Measure Code,Score
48195,343025,Buncombe,NC,I_019_02_DTC_OBS_RATE,70.98

In [57]:
Buncombe_DTC_25=IRF_provider_data_June_25.loc[(IRF_provider_data_June_25['Measure Code']=='I_019_02_DTC_OBS_RATE')& (IRF_provider_data_June_25['County/Parish']=='Buncombe')]
Buncombe_DTC_25.head()

,CMS Certification Number (CCN),County/Parish,State,Measure Code,Score
48594,343025,Buncombe,NC,I_019_02_DTC_OBS_RATE,70.99

In [58]:
Buncombe_DTC_Merged= pd.merge(Buncombe_DTC_23, Buncombe_DTC_24,
                              on= 'County/Parish',
                              how= 'inner')
Buncombe_DTC_Merged

,CMS Certification Number (CCN)_x,State_x,County/Parish,CMS Region,Measure Code_x,Score_x,CMS Certification Number (CCN)_y,State_y,Measure Code_y,Score_y
0,343025,NC,Buncombe,4,I_019_02_DTC_OBS_RATE,66.30,343025,NC,I_019_02_DTC_OBS_RATE,70.98

In [59]:
Buncombe_DTC_Merged= pd.merge(Buncombe_DTC_Merged, Buncombe_DTC_25,
                              on= 'County/Parish',
                              how= 'inner')
Buncombe_DTC_Merged

,CMS Certification Number (CCN)_x,State_x,County/Parish,CMS Region,Measure Code_x,Score_x,CMS Certification Number (CCN)_y,State_y,Measure Code_y,Score_y,CMS Certification Number (CCN),State,Measure Code,Score
0,343025,NC,Buncombe,4,I_019_02_DTC_OBS_RATE,66.30,343025,NC,I_019_02_DTC_OBS_RATE,70.98,343025,NC,I_019_02_DTC_OBS_RATE,70.99

In [60]:
Buncombe_DTC_Merged=Buncombe_DTC_Merged[['Measure Code','Score_x','Score_y','Score']]
Buncombe_DTC_Merged

            Measure Code Score_x Score_y  Score
0  I_019_02_DTC_OBS_RATE   66.30   70.98  70.99

In [61]:
Buncombe_DTC_Merged=Buncombe_DTC_Merged.rename(columns={'Score_x':'2023 Score','Score_y':'2024 Score','Score':'2025 Score'})
Buncombe_DTC_Merged

            Measure Code 2023 Score 2024 Score 2025 Score
0  I_019_02_DTC_OBS_RATE      66.30      70.98      70.99

In [62]:
Buncombe_DTC_Merged=Buncombe_DTC_Merged[['2023 Score','2024 Score','2025 Score']].astype(str).astype(float)
Buncombe_DTC_Merged

   2023 Score  2024 Score  2025 Score
0        66.3       70.98       70.99

In [63]:
Buncombe_DTC_Merged['Avg DTC Score']=Buncombe_DTC_Merged[['2023 Score','2024 Score','2025 Score']].mean(axis=1)
Buncombe_DTC_Merged

   2023 Score  2024 Score  2025 Score  Avg DTC Score
0        66.3       70.98       70.99      69.423333